version: '2.0'
services:
  python-project:
    image: abc
    command: bash -c "django-admin startproject testing"
    volumes: [".:/usr/src/app"]
  python-sql:
    image: mysql
    volumes: ["./data:/var/lib/mysql"]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: incridea
      MYSQL_USER: shashank
      MYSQL_PASSWORD: shashank
  python-server:
    image: abc
    command: bash -c "cd testing && python manage.py runserver 8888"
    volumes: ['.:/usr/src/app']
    ports: ["3000:8888"]
    depends_on:
      - python-sql